### ISSUE TITLE
MIT License or GPLv3

### ISSUE THREAD

**Issue by wannaphongcom** [kootenpv/sky#2]
This python module using MIT License or GPLv3 ?
Thank you.
My personal thoughts. I want to be the MIT License.

**Comment by kootenpv** [comment]
I chose a license similar to Django, and uploaded it. Thanks for bringing it up!

**Comment by wannaphongcom** [comment]
From https://github.com/kootenpv/sky/blob/master/LICENSE . It's BSD License. Please edit setup.py 
Thank you.
