### ISSUE TITLE
Install fails due to distribute

### ISSUE THREAD

**Issue by Savier** [kootenpv/sky#4]
Package depends on distribute, which is deprecated as far as I know. 

[distribute-fail.txt](https://github.com/kootenpv/sky/files/369866/distribute-fail.txt)

**Comment by kootenpv** [comment]
I have no idea what it is doing there! It has been there forever. 

I published a new build without it; no one else mentioned having problems with it. I hope it works for you with `sky==0.0.196`

**Comment by Savier** [comment]
Thank you, now it installs.
